# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SampleObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteTaskVision', '0.4.1' # Latest versions don't support iOS 12. To support iOS 12 - 0.4.1 version should be used. 0.4.2, 0.4.3 are launchable on iOS 13+.

end
