#source 'git@bitbucket.org:imito/spec.git' #For Xcode Cloud should be commented out.
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '17'

def devPods
  pod 'FileBrowser'
end

target 'Sample' do
  use_frameworks!
  devPods
  pod 'TensorFlowLiteTaskVision', '0.4.3'
end

target 'SampleSimulator' do
  use_frameworks!
  devPods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17'
    end
  end
end
