#source 'git@bitbucket.org:imito/spec.git' #For Xcode Cloud should be commented out.
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16'

def woundgenius
 # pod 'WoundGenius', :path => '..'
end

def devPods
  pod 'FileBrowser'
end

target 'Sample' do
  use_frameworks!
  woundgenius
  devPods
  pod 'TensorFlowLiteTaskVision', '0.4.1' # Latest versions doesn't support iOS 12. To support iOS 12 - 0.4.1 version should be used. 0.4.2, 0.4.3 are launchable on iOS 13+.
end

target 'Sample 3D' do
  use_frameworks!
  woundgenius
  devPods
  pod 'TensorFlowLiteTaskVision', '0.4.1' # Latest versions doesn't support iOS 12. To support iOS 12 - 0.4.1 version should be used. 0.4.2, 0.4.3 are launchable on iOS 13+.
end

target 'SampleSimulator' do
  use_frameworks!
  woundgenius
  devPods
end

target 'SampleTests' do
  use_frameworks!
  woundgenius
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16'
    end
  end
end
